### ISSUE TITLE
Assertion `n.m_buf < 0.0' failed

### ISSUE THREAD

**Issue by linshiyx** [mgbellemare/SkipCTS#4]
I'm not very familiar with the theory of skipcts. I use it with alphabet [0-255]. What does it mean when 'n.m_buf < 0.0 failed' happend? How to avoid it? Thank you.

**Comment by mgbellemare** [comment]
Hi, it means somehow you ended up with a positive probability, or a NaN. This would happen if you actually fed your model more than 256 symbols. If not, it's worth checking what probabilities your model is assigning to the training symbols before the error occurs.

**Comment by linshiyx** [comment]
Thank you. It turn out to be a bug of my implementation of SAD estimator.

**Comment by linshiyx** [comment]
I'm trying to reproduce experiment of your count-based exploration method on Montezuma. It seems to require a large memory for 42*42=1764 location-dependent cts models. Can you give some advice of the size of alphabet and the size of slots per cts model? And how much memory and time is require to do the experiment? Thanks a lot!

**Comment by mgbellemare** [comment]
Unfortunately the Python implementation that's available here is neither fast nor particularly memory efficient. The best thing to do would be to have a good C++ implementation (based on the SkipCTS code that's also here), but realistically I just won't have the time.

Still: alphabet size can be 8 (3-bit grayscale). I didn't use hashing in the original code.

In Ostrovski et al. (2017) we played with a convolutional CTS which didn't work too badly and used a single shared model.

**Comment by linshiyx** [comment]
If alphabet size is 8 then the memory won't be a problem. I have modified and wrapped your C++ implementation of SkipCTS as a Python extention module using pybind11. Thanks for advice!
